version: "2"

run:
  modules-download-mode: readonly

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    # 1. This is the default enabled set of golangci
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # 2. These are not part of the default set
    - depguard
    - unconvert
    - misspell
    - revive
    - gocritic
    - forbidigo

  settings:
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          arguments:
            - allowStrs: '""'
              allowInts: '0,1,-1'
        - name: cognitive-complexity
          arguments: [25]
        - name: max-public-structs
          arguments: [10]
        # Disabled
        - name: line-length-limit
          # Formatter `golines` takes care of this.
          disabled: true

    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - $gostd
            - github.com/urfave/cli
            - go.einride.tech/here/geocodingsearchv7
            - go.farcloser.world/core
            - github.com/apostasie/thota
    staticcheck:
      checks:
        - all

formatters:
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/containerd)
        - localmodule
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
    gofumpt:
      extra-rules: true
  enable:
    - gci
    - gofmt
    - gofumpt
    - golines
    - goimports
  exclusions:
    generated: disable
